tweak workflow

diff --git a/.github/workflows/build-msi.yaml b/.github/workflows/build-msi.yaml
--- a/.github/workflows/build-msi.yaml
+++ b/.github/workflows/build-msi.yaml
@@ -1,6 +1,12 @@
 name: Build MSI
 
-on: [push]
+on:
+  workflow_dispatch:
+    inputs:
+      # since this is being triggered manually on branch but we should use our regular git tags when we're back on the normal flow
+      msi_version:
+        description: "MSI package version (e.g., 1.0.0)"
+        required: true
 
 jobs:
   build-msi:
@@ -10,6 +16,21 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Install GitHub CLI
+        run: |
+          choco install gh --yes
+
+      # Step 3: Only needed while we provide manual versions
+      - name: Check for existing version
+        shell: bash
+        run: |
+          if gh release view | grep "agent-${{ github.event.inputs.msi_version }}.msi"; then
+            echo "Error: An artifact with version '${{ github.event.inputs.msi_version }}' already exists. Please increment the version."
+            exit 1
+          fi
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Set up Go
         uses: actions/setup-go@v4
         with:
@@ -18,17 +39,23 @@ jobs:
       - name: Install Make
         run: choco install make --yes
 
-      - name: Install WiX 5.0
+      - name: Install WiX CLI
         run: dotnet tool install --global wix
+
+      - name: Install WiX Extensions
+        run: |
+          wix extension add -g WixToolset.Firewall.wixext/5.0.2
+          wix extension add -g WixToolset.Util.wixext/5.0.2
 
       - name: Build Go binary
         run: make windows
 
       - name: Build MSI
-        run: wix build agent.wxs -define GoBinDir="${{ github.workspace }}" -define MSIProductVersion="0.0.3" -ext WixToolset.Util.wixext -ext WixToolset.Firewall.wixext  -o agent.msi
-
+        run: |
+          wix build agent.wxs -define GoBinDir="${{ github.workspace }}\bin" -define MSIProductVersion="${{ github.event.inputs.msi_version }}" -ext WixToolset.Util.wixext -ext WixToolset.Firewall.wixext -o agent-${{ github.event.inputs.msi_version }}.msi
+    
       - name: Upload MSI artifact
         uses: actions/upload-artifact@v3
         with:
-          name: agent.msi
-          path: agent.msi
+          name: agent-${{ github.event.inputs.msi_version }}.msi
+          path: agent-${{ github.event.inputs.msi_version }}.msi
